In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import load_iris
data=load_iris()

In [3]:
X = data.data
y = data.target

In [4]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.3, random_state=1)

In [8]:
from sklearn.preprocessing import StandardScaler #mean=0, sigma=1
scaler = StandardScaler()
X_train=  scaler.fit_transform(X_train)

In [9]:
from sklearn.decomposition import PCA
pca = PCA()
pca

PCA()

In [11]:
X_test = scaler.transform(X_test)
X_train = pca.fit_transform(X_train)
X_train

array([[ 3.29187211e+00, -1.64765395e-01,  7.27509357e-01,
        -5.78968617e-02],
       [-1.79681257e+00,  1.59337640e+00,  4.43385293e-01,
        -8.32121597e-02],
       [-2.30351105e+00,  8.69431210e-01,  2.33792304e-02,
         2.34275331e-02],
       [-2.02984587e+00, -5.59980278e-01,  3.92793836e-02,
        -1.38513261e-01],
       [ 9.09507841e-03, -9.68249823e-01, -5.55780350e-01,
         3.73471773e-02],
       [-2.09778967e+00,  4.52095658e-01,  1.94589630e-01,
        -1.74901668e-02],
       [-1.96393609e+00,  8.23951366e-01,  5.15626453e-01,
        -2.10836333e-01],
       [ 2.49741981e+00,  2.55439705e+00,  2.78249238e-01,
         2.39201187e-01],
       [ 1.87223188e+00,  6.45015818e-01,  7.34520648e-02,
        -2.04303483e-01],
       [ 2.31306020e+00,  3.19175762e-01,  6.91328103e-01,
         2.17802182e-01],
       [ 1.85690136e+00, -2.09457613e-01, -3.25721459e-01,
        -9.87875317e-02],
       [ 1.17626383e+00, -3.27992385e-01, -1.15904903e-01,
      

In [12]:
X_test = pca.transform(X_test)

In [13]:
pca.components_

array([[ 1.00000000e+00, -3.76214597e-16, -1.25480132e-17,
         1.17142714e-16],
       [ 3.76214597e-16,  1.00000000e+00,  3.87695615e-16,
         7.54783453e-17],
       [ 1.25480132e-17, -3.81639165e-16,  1.00000000e+00,
        -4.21853360e-15],
       [-1.17142714e-16, -5.55111512e-17,  4.17401356e-15,
         1.00000000e+00]])