In [1]:
import numpy as np

In [2]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,4,(3,3))

In [3]:
arr1

array([[2, 1, 2],
       [1, 1, 2],
       [1, 2, 2]], dtype=int32)

In [4]:
arr2

array([[1, 1, 2],
       [3, 3, 1],
       [2, 2, 3]], dtype=int32)

In [5]:
#flatten an array >> gives one dimensional array as output
arr1.flatten()

array([2, 1, 2, 1, 1, 2, 1, 2, 2], dtype=int32)

In [6]:
arr1

array([[2, 1, 2],
       [1, 1, 2],
       [1, 2, 2]], dtype=int32)

In [7]:
arr=np.array([1,2,3,4])
#to expand the dimension of the array 
np.expand_dims(arr,axis=0) #axis 0 means row wise(x-axis) and 1 means column wise (y-axis)

array([[1, 2, 3, 4]])

In [8]:
#to reduce the dimension
np.squeeze(arr)

array([1, 2, 3, 4])

In [9]:
arr2

array([[1, 1, 2],
       [3, 3, 1],
       [2, 2, 3]], dtype=int32)

In [10]:
np.repeat(arr2, 3 ,axis=0)

array([[1, 1, 2],
       [1, 1, 2],
       [1, 1, 2],
       [3, 3, 1],
       [3, 3, 1],
       [3, 3, 1],
       [2, 2, 3],
       [2, 2, 3],
       [2, 2, 3]], dtype=int32)

In [11]:
arr2

array([[1, 1, 2],
       [3, 3, 1],
       [2, 2, 3]], dtype=int32)

In [13]:
np.roll(arr2,-1) #first element became last element and every other element has moved forward we can use -2 -3 -4 anything there based on our need

array([[1, 2, 3],
       [3, 1, 2],
       [2, 3, 1]], dtype=int32)

In [14]:
~arr2 # negative of each element with one up

array([[-2, -2, -3],
       [-4, -4, -2],
       [-3, -3, -4]], dtype=int32)

In [15]:
#string array 
d=np.array(['bindhu','got','into','kaist'])
d

array(['bindhu', 'got', 'into', 'kaist'], dtype='<U6')

In [16]:
np.char.upper(d)# to convert all strings into uppercase

array(['BINDHU', 'GOT', 'INTO', 'KAIST'], dtype='<U6')

In [17]:
arr1

array([[2, 1, 2],
       [1, 1, 2],
       [1, 2, 2]], dtype=int32)

In [18]:
np.sin(arr1)

array([[0.90929743, 0.84147098, 0.90929743],
       [0.84147098, 0.84147098, 0.90929743],
       [0.84147098, 0.90929743, 0.90929743]])

In [22]:
np.tan(arr1) #only has sin cos and tan

array([[-2.18503986,  1.55740772, -2.18503986],
       [ 1.55740772,  1.55740772, -2.18503986],
       [ 1.55740772, -2.18503986, -2.18503986]])

In [23]:
np.log10(arr1)

array([[0.30103, 0.     , 0.30103],
       [0.     , 0.     , 0.30103],
       [0.     , 0.30103, 0.30103]])

In [24]:
np.exp(arr1)

array([[7.3890561 , 2.71828183, 7.3890561 ],
       [2.71828183, 2.71828183, 7.3890561 ],
       [2.71828183, 7.3890561 , 7.3890561 ]])

In [25]:
np.power(arr1,3) # goes index wise arr[1]^3 does the same thing for all elements

array([[8, 1, 8],
       [1, 1, 8],
       [1, 8, 8]], dtype=int32)

In [26]:
#to get max value from the array
np.max(arr1)

np.int32(2)

In [27]:
np.min(arr1)

np.int32(1)

In [28]:
np.mean(arr1)

np.float64(1.5555555555555556)

In [29]:
np.std(arr1)

np.float64(0.4969039949999533)

In [30]:
np.var(arr1)

np.float64(0.2469135802469136)

In [31]:
np.subtract(arr1,arr2) #same result as arr1 - arr2

array([[ 1,  0,  0],
       [-2, -2,  1],
       [-1,  0, -1]], dtype=int32)

In [33]:
np.multiply(arr1,arr2)

array([[2, 1, 4],
       [3, 3, 2],
       [2, 4, 6]], dtype=int32)

In [34]:
np.mod(arr1,arr2) # returns element wise remainder

array([[0, 0, 0],
       [1, 1, 0],
       [1, 0, 2]], dtype=int32)

In [37]:
np.sort(arr1) # returns sorted elements in ascending order in row wise sort

array([[1, 2, 2],
       [1, 1, 2],
       [1, 2, 2]], dtype=int32)

In [38]:
arr1

array([[2, 1, 2],
       [1, 1, 2],
       [1, 2, 2]], dtype=int32)

In [40]:
np.count_nonzero(arr1)

np.int64(9)

In [42]:
np.where(arr1>0)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [43]:
import numpy.matlib as nm

In [45]:
nm.zeros(5,dtype=int)

matrix([[0, 0, 0, 0, 0]])

In [46]:
np.linalg.inv(arr1) # inverse of the matrix

array([[ 1.00000000e+00, -1.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00, -1.00000000e+00,  1.00000000e+00],
       [-5.00000000e-01,  1.50000000e+00, -5.00000000e-01]])